CREATE TABLE article(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(20) NOT NULL,
    publishedOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    body VARCHAR(6000) NOT NULL
)

CREATE TABLE comment {
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL FOREIGN KEY,
    content VARCHAR(200) NOT NULL
}